In [3]:
import pandas as pd
import re
import nltk
nltk.download("vader_lexicon")
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\shaik_be\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [81]:
data = r"C:\Users\shaik_be\Desktop\McDonald_s_Reviews.csv"
df = pd.read_csv(data, encoding='unicode_escape')
df.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating
0,1,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,Why does it look like someone spit on my food?...,1 star
1,2,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,It'd McDonalds. It is what it is as far as the...,4 stars
2,3,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Made a mobile order got to the speaker and che...,1 star
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc. Crispy chicken sandwich was ï¿½ï¿½ï¿½ï¿...,5 stars
4,5,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",2 months ago,"I repeat my order 3 times in the drive thru, a...",1 star

In [83]:
rev = df[["review", "review_time","rating"]]
rev.head()

                                              review   review_time   rating
0  Why does it look like someone spit on my food?...  3 months ago   1 star
1  It'd McDonalds. It is what it is as far as the...    5 days ago  4 stars
2  Made a mobile order got to the speaker and che...    5 days ago   1 star
3  My mc. Crispy chicken sandwich was ï¿½ï¿½ï¿½ï¿...   a month ago  5 stars
4  I repeat my order 3 times in the drive thru, a...  2 months ago   1 star

In [87]:
def special_char(text):
    text = str(text)
    cleaned_text = re.sub("[^a-zA-Z0-9\n\r'.]" , "", text)
    return cleaned_text
rev['cleaned_review'] = rev['review'].apply(special_char)
rev[["review", "cleaned_review"]].head(15)

C:\Users\shaik_be\AppData\Local\Temp\ipykernel_24256\2890844004.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rev['cleaned_review'] = rev['review'].apply(special_char)

,review,cleaned_review
0,Why does it look like someone spit on my food?...,Whydoesitlooklikesomeonespitonmyfood\nIhadanor...
1,It'd McDonalds. It is what it is as far as the...,It'dMcDonalds.Itiswhatitisasfarasthefoodandatm...
2,Made a mobile order got to the speaker and che...,Madeamobileordergottothespeakerandcheckeditin....
3,My mc. Crispy chicken sandwich was ï¿½ï¿½ï¿½ï¿...,Mymc.Crispychickensandwichwascustomerservicewa...
4,"I repeat my order 3 times in the drive thru, a...",Irepeatmyorder3timesinthedrivethruandshestillm...
5,I work for door dash and they locked us all ou...,Iworkfordoordashandtheylockedusallouttowaitina...
6,If I could give this location a zero on custo...,IfIcouldgivethislocationazerooncustomerservice...
7,Came in and ordered a Large coffee w/no ice. T...,CameinandorderedaLargecoffeewnoice.Theyhandedm...
8,Went thru drive thru. Ordered. Getting home no...,Wentthrudrivethru.Ordered.Gettinghomenoticedmy...
9,"I'm not really a huge fan of fast food, but I ...",I'mnotreallyahugefanoffastfoodbutIhave2teenage...
10,Worst McDonaldï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿...,WorstMcDonald
11,We stopped by for a quick breakfast. It was n...,Westoppedbyforaquickbreakfast.Itwasnotcrowdedi...
12,The morning crew seems fast and efficient. Nig...,Themorningcrewseemsfastandefficient.Nightcrewi...
13,"Today, i was disappointed in that restaurant #...",Todayiwasdisappointedinthatrestaurant11853didn...
14,Ordered food burger wrong and left out part of...,Orderedfoodburgerwrongandleftoutpartoftheorder...

In [89]:
del rev["review"]

In [39]:
rev["rating"]

0         1 star
1        4 stars
2         1 star
3        5 stars
4         1 star
          ...
33391     1 star
33392    5 stars
33393    4 stars
33394    5 stars
33395    5 stars
Name: rating, Length: 33396, dtype: object

In [91]:
rev["numeric_rating"] = rev['rating'].str.extract('(\d+)').astype(float)
rev["numeric_rating"]

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\shaik_be\AppData\Local\Temp\ipykernel_24256\2968990051.py:1: SyntaxWarning: invalid escape sequence '\d'
  rev["numeric_rating"] = rev['rating'].str.extract('(\d+)').astype(float)
C:\Users\shaik_be\AppData\Local\Temp\ipykernel_24256\2968990051.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rev["numeric_rating"] = rev['rating'].str.extract('(\d+)').astype(float)

0        1.0
1        4.0
2        1.0
3        5.0
4        1.0
        ...
33391    1.0
33392    5.0
33393    4.0
33394    5.0
33395    5.0
Name: numeric_rating, Length: 33396, dtype: float64

In [43]:
rev["review_time"]

0        3 months ago
1          5 days ago
2          5 days ago
3         a month ago
4        2 months ago
             ...
33391     4 years ago
33392      a year ago
33393      a year ago
33394     5 years ago
33395     2 years ago
Name: review_time, Length: 33396, dtype: object

In [93]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

# Function to convert time periods to datetime objects
def convert_to_datetime(period):
    if 'year' in period:
        if period.split()[0].isdigit():
            num_years = int(period.split()[0])
            return datetime.now() - relativedelta(years=num_years)
    elif 'month' in period:
        if period.split()[0].isdigit():
            num_months = int(period.split()[0])
            return datetime.now() - relativedelta(months=num_months)
    elif 'week' in period:
        if period.split()[0].isdigit():
            num_weeks = int(period.split()[0])
            return datetime.now() - relativedelta(weeks=num_weeks)
    elif 'day' in period:
        if period.split()[0].isdigit():
            num_days = int(period.split()[0])
            return datetime.now() - relativedelta(days=num_days)
    return None  # Return None for unmatched patterns

# Apply the function to the 'review_time' column and create a new 'modified_review_time' column with only the dates
rev['modified_review_time'] = rev['review_time'].apply(lambda x: convert_to_datetime(x).date() if convert_to_datetime(x) else "Unknown Date")
rev[["review_time", "modified_review_time"]]

C:\Users\shaik_be\AppData\Local\Temp\ipykernel_24256\4120006029.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rev['modified_review_time'] = rev['review_time'].apply(lambda x: convert_to_datetime(x).date() if convert_to_datetime(x) else "Unknown Date")

        review_time modified_review_time
0      3 months ago           2024-09-20
1        5 days ago           2024-12-15
2        5 days ago           2024-12-15
3       a month ago         Unknown Date
4      2 months ago           2024-10-20
...             ...                  ...
33391   4 years ago           2020-12-20
33392    a year ago         Unknown Date
33393    a year ago         Unknown Date
33394   5 years ago           2019-12-20
33395   2 years ago           2022-12-20

[33396 rows x 2 columns]

In [95]:

rev["modified_review_time"] = pd.to_datetime(rev['modified_review_time'], errors='coerce')

grouped_dates = rev.groupby(rev['modified_review_time'].dt.year)['modified_review_time'].count()

C:\Users\shaik_be\AppData\Local\Temp\ipykernel_24256\2977958114.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rev["modified_review_time"] = pd.to_datetime(rev['modified_review_time'], errors='coerce')

In [97]:
print(grouped_dates)

modified_review_time
2012.0       4
2013.0      10
2014.0      38
2015.0      52
2016.0      91
2017.0     387
2018.0    1679
2019.0    4306
2020.0    6740
2021.0    5522
2022.0    3892
2024.0    5224
Name: modified_review_time, dtype: int64

In [99]:
random_rev = rev['cleaned_review'][100]
random_rev

"IlovegoingtoMcDonald'sinthatareabecausethat'swhereIgetmostofmyfoodformyfamilyandmygrandchildrenandtheylovemewhenIbringstufftohimlikeeverycoupledayssoit'sgreattogotothatMcDonald'sMcDonald'sisagoodspotfortakingmygrandkidsandbuyhimfoodtherearethegreatestthingthatthey'rerightoffoflakeCreekthankyouforputtingitthere"

In [101]:
analyzer= SentimentIntensityAnalyzer()
analyzer.polarity_scores(random_rev)

{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [109]:
analyzer = SentimentIntensityAnalyzer()

body = rev.cleaned_review
neg, neu, pos, compound, tag = [], [], [], [], []

for review in body:
    res = analyzer.polarity_scores(str(review))
    neg.append(res['neg'])
    neu.append(res['neu'])
    pos.append(res['pos'])
    compound.append(res['compound'])

    # Assigning sentiment tags based on VADER scores for each review
    if res['compound'] >= 0.05:
        tag.append("Positive")
    elif res['compound'] <= -0.05:
        tag.append("Negative")
    else:
        tag.append("Neutral")

# Append results to the dataframe
rev["Negative"] = neg
rev["Neutral"] = neu
rev["Positive"] = pos
rev["Compound"] = compound
rev["Sentiment_Tag"] = tag

In [105]:
rev.tail(10)

,review_time,rating,cleaned_review,numeric_rating,modified_review_time,Negative,Neutral,Positive,Compound,Sentiment_Tag
33386,a year ago,5 stars,Greatinfastfood,5.0,NaT,0.0,1.0,0.0,0.0,Neutral
33387,6 years ago,5 stars,Excellentlocationandverygoodatmosphereexcellen...,5.0,2018-12-20,0.0,1.0,0.0,0.0,Neutral
33388,3 years ago,5 stars,Allverygoodfoodattention,5.0,2021-12-20,0.0,1.0,0.0,0.0,Neutral
33389,5 years ago,4 stars,QuietopenthelocalJanuary1.,4.0,2019-12-20,0.0,1.0,0.0,0.0,Neutral
33390,a year ago,5 stars,Very.Well,5.0,NaT,0.0,1.0,0.0,0.0,Neutral
33391,4 years ago,1 star,Theytreatedmeverybadly.,1.0,2020-12-20,0.0,1.0,0.0,0.0,Neutral
33392,a year ago,5 stars,Theserviceisverygood,5.0,NaT,0.0,1.0,0.0,0.0,Neutral
33393,a year ago,4 stars,Toremovehungerisenough,4.0,NaT,0.0,1.0,0.0,0.0,Neutral
33394,5 years ago,5 stars,It'sgoodbutlatelyithasbecomeveryexpensive.,5.0,2019-12-20,0.0,1.0,0.0,0.0,Neutral
33395,2 years ago,5 stars,theytookgoodcareofme,5.0,2022-12-20,0.0,1.0,0.0,0.0,Neutral

In [111]:
rev["Sentiment_Tag"].value_counts()

Sentiment_Tag
Neutral     28619
Positive     4019
Negative      758
Name: count, dtype: int64